### ISSUE TITLE
Variable names changed when using import

### ISSUE THREAD

**Issue by awa2** [grant/ts2gas#16]
```TypeScript
// foo.ts
import Module from 'TypeScriptModule';
const module = new Module();
```
It transpiled below:
```JavaScript
// foo.gs
var module = new TypeScriptModule_1["default"]()
```
So, `TypeScriptModule_1 is not found` error has occuerd.

----
I know ignoring import/export statements has merged at issue#5, and it's a great work!
Adding `_1` into module variable name when using TS module import, is it properly transpiling or not ?
If it's correct convert of TypeScript, I should update my TypeScript codes for Google Apps Script.
How should I do ?

@grant  @PopGoesTheWza

**Comment by PopGoesTheWza** [comment]
@awa2 (cc @grant )
It looks like `ts.transpileModule()` when given:
```ts
import Module from 'TypeScriptModule';
```
transpile it into
```js
var TypeScriptModule_1 = require("TypeScriptModule");
var module = new TypeScriptModule_1["default"]();
```
and ts2gas is dropping the first statement.

Q1: which version of ts2gas are you using?
Q2: since `require()`is not support by GAS, what output would you expect/deem correct?

**Comment by PopGoesTheWza** [comment]
@awa2 @grant I have a fix which I will PR asap

**Comment by awa2** [comment]
Thank you, @PopGoesTheWza !

I got #17 and tried it.
It seemed that issue has fixed, but there are breaking changes from ts2gas@1.3.0.
I'm using ts2gas@1.3.0 with clasp, so it 

Transpile differences between `ts2gas@1.3.0` and `ts2gas@`e955994 are below: 

### Original TS code
```TypeScript
import Module from 'TypeScriptModule';
const module = new Module();
```
### ts2gas@1.3.0 with typescript@3.2.2
```JavaScript
// import Module from "TypeScriptModule";
var module = new Module();
```
This is what I expect.

### ts2gas@e955994 with typescript@3.2.2
```JavaScript
var module = new TypeScriptModule["default"]();
```
`"TypeSciprtModule" is not defined` error has occurred.

And also, require statements has something with wrong.
```TypeScript
import { SubModule } from "TypeScriptModule";
const subModule = new SubModule();
```
vvv
```JavaScript
var subModule = new ./TypeScriptModule.SubModule();
```
it makes syntax error.

I respect your TypeScript understanding and quick response for fixing.
I hope ts2gas@1.3.0 type convert because it makes to be useful for import/export using with Google Apps Script.

**Comment by PopGoesTheWza** [comment]
@awa2 i have `var module = new Module();`fixed (no commit yet)
regarding the submodules, can you  please try with ts2gas 1.3.0 and 1.5.0 the following:
```ts
import { SubModule1, Submodule2 } from "TypeScriptModule";
const subModule1 = new SubModule1();
const subModule2 = new SubModule2();
```

**Comment by PopGoesTheWza** [comment]
@awa2 if you want to test the latest PR which as been merged...

**Comment by awa2** [comment]
@PopGoesTheWza 
I tested #20 , and it looks like all be good!

```TypeScript
import { SubModule1, Submodule2 } from "TypeScriptModule";
const subModule1 = new SubModule1();
const subModule2 = new SubModule2();
```
vvv
```JavaScript
//import { SubModule1, Submodule2 } from "TypeScriptModule";
var subModule1 = new SubModule1();
var subModule2 = new SubModule2();
```

Thank you!
