### ISSUE TITLE
Error in tsconfig.json when npm installed

### ISSUE THREAD

**Issue by dustinmichels** [grant/ts2gas#28]
I ran `npm install ts2gas` and installed version 1.6.0. My IDE warns me about an error in the "tsconfig.json" file:

```
File '/Users/.../node_modules/ts2gas/src/index.ts' not found.
```

Is something configured incorrectly?

**Comment by grant** [comment]
I'm not able to repro this issue.
Can you provide more detail?

This is what I see:
```
npm install ts2gas
npm WARN saveError ENOENT: no such file or directory, open '/Documents/trash/ts2gas-test/test/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Documents/trash/ts2gas-test/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

+ ts2gas@1.6.0
added 2 packages from 2 contributors in 1.693s


   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │       New minor version of npm available! 6.5.0 → 6.9.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.9.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯
```

**Comment by grant** [comment]
Please provide more details in future issue reports.

**Comment by dustinmichels** [comment]
The original error I saw was not in the terminal after running `npm install`, but rather something my IDE (VS Code) flagged about the actual `tsconfig.json` file in my `node_modules/` directory. Since the IDE wasn't complaining about any other files in the node dir, I thought something might be weirdly configured.

I'm having trouble reproducing the error now, though. I apologize for the low-quality issue.

**Comment by grant** [comment]
That's fine. My terseness is just to triage the issue.
Thanks for using clasp!
