### ISSUE TITLE
Improper conversion of [...string]

### ISSUE THREAD

**Issue by axtens** [grant/ts2gas#45]
In VSCode I have 
```javascript
const Reverse = (string:string) => [...string].reverse().join('');
```
ts2gas converts this to 
```javascript
var Reverse = function (string) { return string.slice().reverse().join(''); };
```
which fails because slice does not convert string into an array, which reverse() requires. There is a String.prototype.slice but it is not the same as Array.prototype.slice.

**Comment by PopGoesTheWza** [comment]
@axtens Have you checked if this isn't a known Typescript issue? `ts2gas` only uses Typescript `transpileModule` with sensible presets.

**Comment by PopGoesTheWza** [comment]
@axtens Can you provide an update about this issue?

**Comment by flaming-codes** [comment]
When using ts2gas 3.6.1 in my project, spreading the string gets handled correctly. I think we can close this issue.
