### ISSUE TITLE
(minor) multiple lines import statement improperly commented out

### ISSUE THREAD

**Issue by PopGoesTheWza** [grant/ts2gas#5]
This is minor but if you have a long import statement and spread it on multiple lines, only the first line gets commented out... which cause errors obviously.

**Comment by grant** [comment]
Yes, this is a bug.
I'm not sure how to fix it. Maybe it would require parsing the TS.

**Comment by PopGoesTheWza** [comment]
@gran looking at TypeScript source I ran into its TransformationAPI. It is not documented on the website nor the GitHub wiki but there are a few tests using it.
Broadly, it allows to attach to the transpiler options arrays of callback functions before and after transpiling (not relevant here but there is also an afterDeclaration which is used when emiting .d.ts)
Those callbacks can check the context (import/export declarations for example) and modify the output.
I have good hopes of using this to handle the pre and post transformations.

**Comment by grant** [comment]
LMK if #9 fixes this, so we can close this issue.
Thanks!

**Comment by PopGoesTheWza** [comment]
Latest PR address the issue
